/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface FixedPropertiesJs {
  manufacturer: string
  firmwareVersion: string
  isVirtual: boolean
  spec: string
}

export declare function getFixedProperties(): Promise<FixedPropertiesJs>

export declare function isAvailable(): Promise<boolean>
