/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function activateCredential(opts: ActivateCredentialOptionsJs): Promise<Buffer>

export interface ActivateCredentialOptionsJs {
  akBlob: AkBlobJs
  credentialBlob: Buffer
  secret: Buffer
}

export interface AkBlobJs {
  public: Buffer
  private: Buffer
}

export declare function createKey(opts?: KeyCreateOptionsJs | undefined | null): Promise<KeyCreateResultJs>

export declare function decryptKeyBlob(opts: DecryptKeyBlobOptionsJs): Promise<Buffer>

export interface DecryptKeyBlobOptionsJs {
  keyBlob: AkBlobJs
  cipher: Buffer
}

export interface FixedPropertiesJs {
  manufacturer: string
  firmwareVersion: string
  isVirtual: boolean
  spec: string
}

export declare function getFixedProperties(): Promise<FixedPropertiesJs>

export declare function isAvailable(): Promise<boolean>

export declare function keyBlobPublicDer(keyBlob: AkBlobJs): Promise<Buffer>

export interface KeyCreateOptionsJs {
  keyType?: string
  sign?: boolean
  decrypt?: boolean
}

export interface KeyCreateResultJs {
  publicKeyDer: Buffer
  keyBlob: AkBlobJs
}

export declare function nvDefine(opts: NvDefineOptionsJs): Promise<void>

export interface NvDefineOptionsJs {
  handle: string
  size: number
  auth?: Buffer
  ownerAuth?: Buffer
}

export declare function nvRead(handle: string, offset?: number | undefined | null, size?: number | undefined | null, auth?: Buffer | undefined | null): Promise<Buffer>

export declare function nvReadPublic(handle: string): Promise<NvReadPublicJs>

export interface NvReadPublicJs {
  dataSize: number
  attributes: number
}

export declare function nvUndefine(opts: NvUndefineOptionsJs): Promise<void>

export interface NvUndefineOptionsJs {
  handle: string
  ownerAuth?: Buffer
}

export declare function nvWrite(opts: NvWriteOptionsJs): Promise<void>

export interface NvWriteOptionsJs {
  handle: string
  data: Buffer
  offset?: number
  auth?: Buffer
}

export declare function pcrExtend(index: number, digest: Buffer): Promise<void>

export declare function pcrRead(selection: Array<number>, bank?: string | undefined | null): Promise<Record<string, string>>

export declare function provisionAk(opts?: ProvisionAkOptionsJs | undefined | null): Promise<ProvisionAkJs>

export interface ProvisionAkJs {
  akPublicDer: Buffer
  akBlob: AkBlobJs
}

export interface ProvisionAkOptionsJs {
  keyName?: string
  /** Windows only: `"user"` (default) or `"machine"`. */
  scope?: string
  /** Windows only: replace existing persisted key of the same name. */
  overwrite?: boolean
}

export declare function quote(opts: QuoteOptionsJs): Promise<QuoteJs>

export interface QuoteJs {
  message: Buffer
  signature: Buffer
}

export interface QuoteOptionsJs {
  akBlob: AkBlobJs
  pcrSelection: Array<number>
  qualifyingData: Buffer
  bank?: string
}

export declare function randomBytes(count: number): Promise<Buffer>

export declare function readEkCertificate(): Promise<Buffer | null>

export declare function readPublic(handle: string): Promise<ReadPublicJs>

export interface ReadPublicJs {
  publicKeyDer: Buffer
  name: Buffer
}

export declare function seal(opts: SealOptionsJs): Promise<Buffer>

export interface SealOptionsJs {
  data: Buffer
  pcrSelection?: Array<number>
}

export declare function signKeyBlob(opts: SignKeyBlobOptionsJs): Promise<Buffer>

export interface SignKeyBlobOptionsJs {
  keyBlob: AkBlobJs
  digest: Buffer
}

export declare function unseal(blob: Buffer): Promise<Buffer>
