/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function activateCredential(opts: ActivateCredentialOptionsJs): Promise<Buffer>

export interface ActivateCredentialOptionsJs {
  akBlob: AkBlobJs
  credentialBlob: Buffer
  secret: Buffer
}

export interface AkBlobJs {
  public: Buffer
  private: Buffer
}

export interface FixedPropertiesJs {
  manufacturer: string
  firmwareVersion: string
  isVirtual: boolean
  spec: string
}

export declare function getFixedProperties(): Promise<FixedPropertiesJs>

export declare function isAvailable(): Promise<boolean>

export declare function pcrRead(selection: Array<number>, bank?: string | undefined | null): Promise<Record<string, string>>

export declare function provisionAk(opts?: {
  keyName?: string
  scope?: 'user' | 'machine'
  overwrite?: boolean
}): Promise<ProvisionAkJs>

export interface ProvisionAkJs {
  akPublicDer: Buffer
  akBlob: AkBlobJs
}

export declare function quote(opts: QuoteOptionsJs): Promise<QuoteJs>

export interface QuoteJs {
  message: Buffer
  signature: Buffer
}

export interface QuoteOptionsJs {
  akBlob: AkBlobJs
  pcrSelection: Array<number>
  qualifyingData: Buffer
  bank?: string
}

export declare function readEkCertificate(): Promise<Buffer | null>

export declare function readPublic(handle: string): Promise<ReadPublicJs>

export interface ReadPublicJs {
  publicKeyDer: Buffer
  name: Buffer
}
